# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77bb3606e2c536f7cf2bf32803cf7a07e12e5b25ffb667bbecfb57db0a0b02c2e9c7aa767019be53b2ae9c23cb93aa35e26959b951bf937d9f546423e6a9e492

test:
  secret_key_base: ee2a4d37bd4db1dfa1429729d434daf12890e4a0764bbd7ca4791ffd616fe3ffcc353b81e70a8e93f6845a562a342335250b349a746eef4603557e1009e94b15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
